on: workflow_dispatch

name: PBP Rebuild

jobs:
  update:
    name: PBP Rebuild
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install remotes and nflfastR
        run: |
          install.packages("remotes")
          remotes::install_github("mrcaseb/nflfastR", dependencies = TRUE, type = "both")
        shell: Rscript {0}
      - name: Install necessary packages
        run: |
          install.packages(c("readr", "arrow", "callr"), dependencies = TRUE, type = "both")
        shell: Rscript {0}
      - name: Run update script
        run: Rscript -e 'source("R/update_all_seasons_pbp.R")'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull
          Rscript -e 'source("R/make_pbp_commit.R")'
          git push origin master || echo "No changes to commit"
