name: Merge Upstream
on: 
  schedule:
    - cron: '0 22,23,0,1,2,3,4,5 * * *'

jobs:
  merge-upstream:
    runs-on: macOS-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: upstream
          fetch-depth: 0 
      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: guga31bb/nflfastR-data
          upstream-branch: master
          branch: upstream
